apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: devops-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ammarsysadmin/backend:v2
          ports:
            - containerPort: 5001
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secret 
